"use strict"
// MODO RESTRITO, IMPORTANTE PARA DEIXAR O CÓDIGO MAIS LIMPO
// SE DECLAROU UMA VARIÁVEL, DEVE USAR!
// NÃO PODE DECLARAR UMA VARIÁVEL SEM O TIPO, POR EXEMPLO: nome = "BRUNO"
let nome = "BRUNO"
console.log(`OLÁ ${nome}.`)

// LET - FOI CRIADA PARA SER USADA AONDE FOI CRIADA
