"use strict" // MODO RESTRITO, IMPORTANTE PARA DEIXAR O CÓDIGO MAIS LIMPO
// SE DECLAROU UMA VARIÁVEL, DEVE USAR!
nome = "BRUNO"
console.log(`OLÁ ${nome}.`)

// LET - FOI CRIADA PARA SER USADA AONDE FOI CRIADA

var idade = 40;
